### PR TITLE
Server: JSON rendered with fixtures

### PR DESCRIPTION
**Pull request by bzz**
- [x] Introduce a query string `?json` to the `/` route that will render the output in JSON instead of HTML in the same format as go run main.go -json does
 - [x] Change JSON rendering to be a single document instead of JSONL
 - [x] Add CORS
 - [x] Add `-test` for the server, to load emails from `./fixtures` instead of fetching from Gmail, to simplify the local testing

### CODE REVIEW

**Review by heruka-urgyen — COMMENTED** [review]
Overall, looks good to me. Two comments:

1. We will need cors enabled for comfortable front-end development (for a local server in dev mode; we can pick a particular port to enable or everything from localhost). Not sure if it's in the scope of this PR or not, up to you to decide.

2. Json response comes as a set of loose objects, i.e. `{title: ...}{title: ...}`, instead of something nested in a data structure like `[{title: ...}, {title: ...}]`. Is it by design? Any benefit to it over returning a list of objects? Or am I missing something?

**Comment by bzz** [comment]
1. will add CORS for `-test` mode here
2. you are right, the default output format is by design JSONL as it was for the CLI tooling that follows unix-way convention and plays nicely with the rest of the tools e.g ` | jq .` etc.
    I believe this feedback belongs to #37 but I'll close it and address it here instead

**Comment by bzz** [comment]
Now the server outputs JSON, while CLI still uses JSONL

Before
```
curl -s "http://localhost:8080/?json" | jq -c . | less -S | wc -l
6
```

After
```
curl -s "http://localhost:8080/?json" | jq -c . | less -S | wc -l
1

curl -s "http://localhost:8080/?json" | jq . | less
{
  "read": [],
  "unread": [
    {
      "Title": "Code Generation from Supervised Code Embeddings",
      "URL": "https://link.springer.com/chapter/10.1007/978-3-030-36808-1_42",
      "Author": "H Hu, Q Chen, Z Liu",
      .....
     }, { ... }, ...
   ]
}
```

**Comment by heruka-urgyen** [comment]
Thank you for addressing the comments. LGTM.

**Comment by bzz** [comment]
Thanks for the prompt review!

**Pull request merged**
