### PR TITLE
Server: JSON endpoints

### PR DESCRIPTION
**Pull request by bzz**
- [x] refactoring to use a proper router
 - [x] middleware for handling auth token
 - [x] error messages in JSON that includes redirect URL (for 3-leg OAuth flow using Google)
 - [x] `GET /json/labels` endpoint
 - [x] `GET /json/messages/{labelSlug}` endoint
 - [x] replace the above with `POST /json/messages` \w a label in JSON payload to avoid dealing with label slugs (labels are arbitrary UTF8)
 - [x] add `-test` support for `/json/*`
 - [x] add labels to the fixtures, not only messages

### CODE REVIEW

**Comment by heruka-urgyen** [comment]
Here's what I'm getting when trying to run it

```
go: finding module for package github.com/bzz/scholar-alert-digest/json
cmd/server/server.go:19:2: no matching versions for query "latest"
```
Not sure how to fix it. Seems like the path `github.com/bzz/scholar-alert-digest/json` doesn't exist

**Comment by bzz** [comment]
> Seems like the path `github.com/bzz/scholar-alert-digest/json` doesn't exist

I'm sorry, indeed, I forgot to commit it 🤦 

Fixed now, history re-written.

**Comment by bzz** [comment]
After initial auth though the `/labels` and coping `<base64encoded>` from the cookies

```
curl localhost:8080/json/labels \
    -H 'Cookie: token=<base64encoded>' \
	| jq .

curl -i -X POST -d '{"label":"_test-ml-in-se"}' localhost:8080/json/messages \
    -H 'Cookie: token=<base64encoded>'
```

works 🎉 

The only thing that is left here is to make `/json/*` endpoints respect  `-test`.

**Comment by bzz** [comment]
We now have support for labels and messages fixtures in both, server-side rendering and `/json/*` :shipit: 

Ready to be tested and merged now.

**Review by heruka-urgyen — APPROVED** [review]
This is great. Thank you. LGTM

**Pull request merged**
